dependencies:
  build:
   - maven:3.6.3
   - java:11.0.8
   
build_targets:
  - name: default
    container:
      image: yourbase/yb_ubuntu:18.04
    commands:
      - mvn clean install -Dossindex.fail=false -Dtest=\!UnpackerResourceTest#testPDFImages
ci:
  builds:
    - name: default
      build_target: default
